// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdyguhpiubjthsbkczno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkeWd1aHBpdWJqdGhzYmtjem5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDk3NzQsImV4cCI6MjA3MDk4NTc3NH0.T7uA_DIcOE3LCjGWIv07aKF2q3VQGETBYUYhh6uRJys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});